volumes:
  pg-data:

networks:
  pg-network:

services:
  db:
    container_name: book-db
    image: postgres:16.3-alpine3.19
    restart: always
    volumes:
     - pg-data:/var/lib/postgresql/data
    networks:
      - pg-network
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_DEFAULT_PASSWORD}
    ports:
      - 5432:5432
